import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const packageInfo = require("../package.json");

export const RECORD_TYPES = ["A", "AAAA", "MX", "TXT", "CNAME", "NS", "SRV", "CAA"];
export const OUTPUT_FORMATS = ["text", "json", "bind"];
export const TRANSPORTS = ["ssh", "direct"];
export const EXIT_CODES = {
  0: "success",
  1: "api, ssh, or runtime failure",
  2: "config, auth, or usage failure",
  3: "dry-run prevented a write",
};

export const COMMANDS = [
  {
    name: "capabilities",
    argv: ["capabilities"],
    description: "Emit a machine-readable contract describing commands, flags, formats, transports, and exit codes.",
    mutates: false,
    idempotent: true,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: [],
    requiredFlags: [],
    optionalFlags: ["format"],
    outputs: ["text", "json"],
  },
  {
    name: "doctor",
    argv: ["doctor"],
    description: "Run non-mutating environment readiness checks and a read-only API probe when config is complete.",
    mutates: false,
    idempotent: true,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: [],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "api",
    argv: ["api", "--input", "<path|->"],
    description: "Execute a structured JSON request and return an agent envelope.",
    mutates: true,
    idempotent: false,
    supportsDryRun: true,
    requiresConfirm: false,
    requiredArgs: [],
    requiredFlags: ["input"],
    optionalFlags: ["format"],
    outputs: ["json"],
  },
  {
    name: "auth.check",
    argv: ["auth", "check"],
    description: "Run a read-only CloudNS API probe through the selected transport.",
    mutates: false,
    idempotent: true,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: [],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "zone.list",
    argv: ["zone", "list"],
    description: "List zones visible to the configured CloudNS credentials.",
    mutates: false,
    idempotent: true,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: [],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "zone.add",
    argv: ["zone", "add", "<name>"],
    description: "Add a zone if it does not already exist.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: false,
    requiredArgs: ["name"],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "dry-run", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "zone.remove",
    argv: ["zone", "rm", "<name>"],
    aliases: ["zone.rm"],
    description: "Remove a zone if it exists.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: true,
    requiredArgs: ["name"],
    requiredFlags: ["confirm"],
    optionalFlags: ["transport", "format", "dry-run", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "record.list",
    argv: ["record", "list", "<zone>"],
    description: "List records in a zone, optionally filtered by type and name.",
    mutates: false,
    idempotent: true,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: ["zone"],
    requiredFlags: [],
    optionalFlags: ["type", "name", "transport", "format", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "record.add",
    argv: ["record", "add", "<zone>"],
    description: "Add a DNS record if an equivalent record does not already exist.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: false,
    requiredArgs: ["zone"],
    requiredFlags: ["type", "value"],
    optionalFlags: [
      "name",
      "ttl",
      "priority",
      "weight",
      "port",
      "caa-flag",
      "caa-type",
      "transport",
      "format",
      "dry-run",
      "verbose",
    ],
    outputs: ["text", "json"],
  },
  {
    name: "record.remove",
    argv: ["record", "rm", "<zone>"],
    aliases: ["record.rm"],
    description: "Remove one matching record by id or by type/name/value selector.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: true,
    requiredArgs: ["zone"],
    requiredFlags: ["confirm"],
    optionalFlags: ["id", "type", "name", "value", "transport", "format", "dry-run", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "preset.diff",
    argv: ["preset", "diff", "<zone>", "<preset>"],
    description: "Show additions and removals required for a preset.",
    mutates: false,
    idempotent: true,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: ["zone", "preset"],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "preset.apply",
    argv: ["preset", "apply", "<zone>", "<preset>"],
    description: "Apply missing records from a runtime-safe preset.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: false,
    requiredArgs: ["zone", "preset"],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "dry-run", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "preset.remove",
    argv: ["preset", "remove", "<zone>", "<preset>"],
    description: "Remove live records owned by a runtime-safe preset.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: false,
    requiredArgs: ["zone", "preset"],
    requiredFlags: [],
    optionalFlags: ["transport", "format", "dry-run", "verbose"],
    outputs: ["text", "json"],
  },
  {
    name: "backup.create",
    argv: ["backup", "create", "<zone>"],
    description: "Write a JSON backup or BIND export for a zone.",
    mutates: false,
    idempotent: false,
    supportsDryRun: false,
    requiresConfirm: false,
    requiredArgs: ["zone"],
    requiredFlags: [],
    optionalFlags: ["output", "format", "transport", "verbose"],
    outputs: ["text", "json", "bind"],
  },
  {
    name: "backup.restore",
    argv: ["backup", "restore", "<zone>"],
    description: "Restore records from a JSON backup.",
    mutates: true,
    idempotent: true,
    supportsDryRun: true,
    requiresConfirm: true,
    requiredArgs: ["zone"],
    requiredFlags: ["input", "confirm"],
    optionalFlags: ["transport", "format", "dry-run", "verbose"],
    outputs: ["text", "json"],
  },
];

export function buildCapabilities() {
  return {
    ok: true,
    command: "capabilities",
    status: "ok",
    exitCode: 0,
    data: {
      name: packageInfo.name,
      version: packageInfo.version,
      schemaVersion: 1,
      commands: COMMANDS,
      recordTypes: RECORD_TYPES,
      formats: OUTPUT_FORMATS,
      transports: TRANSPORTS,
      exitCodes: EXIT_CODES,
    },
    warnings: [],
    errors: [],
  };
}
